# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Japan Daily News
description: "Japan Daily News brings you today's news from Japan, powered by AI. This computer-generated daily podcast covers the most important stories from Japan in easy-to-digest 2-minute episodes – listen while brushing your teeth!"
subtitle: "Today's news from Japan – a podcast powered by AI"
lang: en
author: Daniel Davis
copyright: "CC BY-NC-SA 4.0"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://japandailynews.com" # the base hostname & protocol for your site
twitter_username: ourmaninjapan
github_username: tagawa

#permalink: /:year/:title.html

#Timezone
timezone: Asia/Tokyo

#Setup for Pages
include: ['_pages']

# Build settings
markdown: kramdown

#Exclude local build settings
exclude: ['readme.md', 'Gemfile.lock', 'Gemfile']

# Sitemap
url: "https://japandailynews.com" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
